### ISSUE TITLE
[Feat]Support xlsx parser since paimon.moe can't export json directly

### ISSUE THREAD

**Issue by BTMuli** [anishkn04/uigfConverter#1]
Thanks for your support for UIGF!

Review the code,I noticed that this tool can only support `json` format:

```javascript
if (file.type !== "application/json") {
    alert("Wrong file type!");
    reject("Invalid file type");
    return;
}
```

But `paimon.moe` just support export gacha record to Excel(which is `.xlsx`),so it is important to parse `.xlsx` first of all——not only for test,but also for user.

Btw,could you send the test data to [me](mailto:bt-muli@dgp-studio.cn) ?

**Comment by anishkn04** [comment]
Thank you for reaching out!
I know that the site supports only Excel file to export gacha record, considering multiple accounts associated with paimon.moe you have to upload the data of whole paimon.moe account (`.json`) instead of single account's wish data (`.xlsx`).
I have updated the [README](https://github.com/anishkn04/uigfConverter) file with the steps!
